service:
  name: typescript-express-typeorm-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-offline

package: # Optional deployment packaging configuration
  exclude:
    - node_modules/@types/**
    - .idea/**
    - package-lock.json
    - README.md
    - src/**/*.ts
    - src/**/*.js.map
    - tsconfig.json

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: dev

functions:
  app:
    handler: src/handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
